### PR TITLE
Stable Diffusion Parameters in Prompt

### PR DESCRIPTION
**Pull request by clintkittiesmeow**
Added support for parsing additional Stable Diffusion parameters in the prompt, including height, width, steps, cfg_scale, seed, and a negative prompt.  Parameters can be specified with parameter_name=value, for example seed=99997, and anything after "np=" will be considered a negative prompt.

This is my first Pull request ever so sorry if the styling is bad!  Shoutout to @jmoney7823956789378 for helping write and test.

### CODE REVIEW

**Comment by chrisrude** [comment]
Awesome!  Will take a look tomorrow.

**Comment by chrisrude** [comment]
This is really great!  Thanks @clintkittiesmeow for the work and @@jmoney7823956789378 for the assist.  Going to just merge this in as-is.

I'll take a pass later just to make a few formatting changes, but otherwise is good!

**Review by chrisrude — APPROVED** [review]
LGTM
🥇

**Comment by clintkittiesmeow** [comment]
Very cool! Thanks!

**Pull request merged**
